### ISSUE TITLE
Doesn't work in Internet Explorer

### ISSUE THREAD

**Issue by carlpett** [iverberk/nomad-ui#116]
Not high prio, but when having different issues, I tested with Internet Explorer. The app doesn't even render. Doesn't write anything to the console either.
While IE is not a targeted browser understandably, I'm guessing it _should_ work. If nothing else then because it might point to something deeper.

**Comment by jippi** [comment]
@carlpett is it IE11 or Edge thats failing?

**Comment by carlpett** [comment]
IE11

**Comment by jippi** [comment]
@carlpett when travis pushes a new `latest` it should work (tm)

**Comment by jippi** [comment]
@carlpett `latest` work for me in Edge and IE11 now! Thanks for reporting :)
