### ISSUE TITLE
servers overview incorrectly displays leaders in other regions as followers

### ISSUE THREAD

**Issue by bastiaanb** [iverberk/nomad-ui#129]
The servers overview shows but the server leader in the local region as leader, not the leaders in other regions. 
I would expect the same results as `nomad server-members`.
`frontend/src/containers/servers.js` determines leadership by comparison with a single member ID. Needs to be changed, but don't know how yet....

**Comment by bastiaanb** [comment]
OK, apparently the frontend side always simply highlighted the first entry. 
PR #131 makes it use the info supplied by the server side. 
server side to be fixed.

**Comment by jippi** [comment]
fixed in #131
