### ISSUE TITLE
Create a Nomad Job file

### ISSUE THREAD

**Issue by dadgar** [iverberk/nomad-ui#13]
It would be awesome if you could `nomad run nomad-ui.nomad`!

**Comment by iverberk** [comment]
Yep! I'm almost done with the backend implementation. The idea is to package it all up in a single binary that will act as a backend and serve up the javascript client. I'll create the appropriate Nomad file for this. Do you have any preference for an exec or Docker task?

**Comment by themalkolm** [comment]
Would be nice to not have docker dependency :dancer:

**Comment by iverberk** [comment]
@dadgar I've added the jobspec: https://github.com/iverberk/nomad-ui/blob/master/nomad-ui.nomad. Let me know if this works for you!

@themalkolm you can now download a binary from the releases page for your platform. No Docker needed :-)

**Comment by dadgar** [comment]
Looks great. Will deploy it to our Nomad cluster soon! One thing is I would add a constraint that it is on linux given the example binary is linux.

Also it would be cool if you by default searched for the address using `nomad.service.consul` given that is automatically registered.

**Comment by iverberk** [comment]
Done!

**Comment by themalkolm** [comment]
@iverberk thanks, will take a look!
