### ISSUE TITLE
Show timestamps for Task Events and Allocations.

### ISSUE THREAD

**Issue by jemc** [iverberk/nomad-ui#139]
There are a number of places in the CLI where timestamps are shown, but in `nomad-ui`, they are not shown.  Particularly, I'm thinking of the Task Events and Allocations, though there may be other places.

It would be great if `nomad-ui` could show timestamps in these places, to replicate the information viewable in the CLI.

**Comment by jippi** [comment]
@jemc if you hover the dotted "time ago in words" it will show time 

![image](https://cloud.githubusercontent.com/assets/22841/19981904/1aa32598-a204-11e6-81be-aea0e0333d69.png)

is there cases where i've missed them I'm more than willing to add them now :)

**Comment by jemc** [comment]
It appears I'm running an old version of `nomad-ui`, and the new version includes timestamps in expected places where the other version did not.
