### ISSUE TITLE
setup travis to publish executable (or docker image) with updates to master

### ISSUE THREAD

**Issue by ketzacoatl** [iverberk/nomad-ui#14]
With the job spec for nomad, we can easily run the executable release. If a user wishes to test the latest from master, they need to setup NPM and build the project. That isn't terrible, but automation is nice and travis can be setup to publish that executable (or build a docker image), with commits made to master. We could then grab the SHA and update the job spec to test on nomad.

Feel free to close this out if it does not suit your needs or workflow, I just realized it would be a great nice to have when testing out the project's latest features.

**Comment by iverberk** [comment]
@ketzacoatl this is a great idea. Unfortunately there are not a lot of tests yet, but automatically creating releases will be a good start. The project is still in the startup phase where things change rapidly (e.g. the whole backend implementation). I think that I'll setup an automated Docker image build as I'm not sure that I can automatically publish releases to Github. I'll let you know once I've made some progress on this.

**Comment by themalkolm** [comment]
Would be nice to have it automated. It is so much easier to hack around when I can build the same way as maintainers do via Travis.

**Comment by themalkolm** [comment]
I already did the travis part. We will have travis building all binaries and pushing all tagged binaries to github. This will also make it possible later to automate docker image creating.

**Comment by ketzacoatl** [comment]
I don't see this on travis-ci.org, would it be at https://travis-ci.org/iverberk/nomad-ui?

**Comment by themalkolm** [comment]
@ketzacoatl oh, sorry. I meant that I did this in my fork but it is yet to be merged to upstream.

**Comment by themalkolm** [comment]
This one is done.

**Comment by iverberk** [comment]
@themalkolm did great work on this. I will look into publishing the releases automatically today.
