### ISSUE TITLE
Issue in getting the API stats from NOMAD

### ISSUE THREAD

**Issue by obenziane2** [iverberk/nomad-ui#145]
I'm getting these errors when running the nomad-ui via : 
"docker run -e NOMAD_ADDR=10.230.45.40:4648 -p 8000:3000 iverberk/nomad-ui:v0.3.1"

I get a response when i do:

root@lemon:~/nomad-ui# curl  10.230.45.40:4646/v1/jobs

[{"ID":"example","ParentID":"","Name":"example","Type":"service","Priority":50,"Status":"running","StatusDescription":"","JobSummary":{"JobID":"example","Summary":{"cache":{"Queued":0,"Complete":4,"Failed":0,"Running":1,"Starting":0,"Lost":0},"flower-app":{"Queued":0,"Complete":1,"Failed":1,"Running":0,"Starting":0,"Lost":0}},"CreateIndex":3819,"ModifyIndex":4236},"CreateIndex":3819,"ModifyIndex":4227,"JobModifyIndex":3957},{"ID":"flower","ParentID":"","Name":"flower","Type":"service","Priority":50,"Status":"running","StatusDescription":"","JobSummary":{"JobID":"flower","Summary":{"flower-app":{"Queued":0,"Complete":5,"Failed":0,"Running":1,"Starting":0,"Lost":0}},"CreateIndex":4119,"ModifyIndex":4272},"CreateIndex":4119,"ModifyIndex":4266,"JobModifyIndex":4266}]
-----
Nomad v0.4.1
Ubuntu 14.04 TLS
----

Error:

20:06:45.663 nomad.go:168 ▶ ERRO  watch: unable to fetch allocations: Get /v1/allocations?index=1&wait=60000ms: unsupported protocol scheme ""
20:06:45.663 nomad.go:189 ▶ ERRO  watch: unable to fetch evaluations: Get /v1/evaluations?index=1&wait=60000ms: unsupported protocol scheme ""
20:06:45.664 nomad.go:210 ▶ ERRO  watch: unable to fetch jobs: Get /v1/jobs?index=1&wait=60000ms: unsupported protocol scheme ""
20:06:45.664 nomad.go:231 ▶ ERRO  watch: unable to fetch nodes: Get /v1/nodes?index=1&wait=60000ms: unsupported protocol scheme ""
20:06:45.664 nomad.go:251 ▶ ERRO  watch: unable to fetch members: Get /v1/agent/members?wait=60000ms: unsupported protocol scheme ""
20:06:55.664 nomad.go:168 ▶ ERRO  watch: unable to fetch allocations: Get /v1/allocations?index=1&wait=60000ms: unsupported protocol scheme ""
20:06:55.664 nomad.go:189 ▶ ERRO  watch: unable to fetch evaluations: Get /v1/evaluations?index=1&wait=60000ms: unsupported protocol scheme ""
20:06:55.664 nomad.go:210 ▶ ERRO  watch: unable to fetch jobs: Get /v1/jobs?index=1&wait=60000ms: unsupported protocol scheme ""
20:06:55.665 nomad.go:251 ▶ ERRO  watch: unable to fetch members: Get /v1/agent/members?wait=60000ms: unsupported protocol scheme ""
20:06:55.665 nomad.go:231 ▶ ERRO  watch: unable to fetch nodes: Get /v1/nodes?index=1&wait=60000ms: unsupported protocol scheme ""

**Comment by jippi** [comment]
Please use `NOMAD_ADDR=http://10.230.45.40:4648` :)

**Comment by obenziane2** [comment]
different issue

21:59:04.060 main.go:86 ▶ INFO  | web.listen-address : 0.0.0.0:3000                                  |
21:59:04.061 main.go:87 ▶ INFO  ----------------------------------------------------------------------
21:59:04.061 main.go:88 ▶ INFO  
21:59:04.061 main.go:92 ▶ INFO  Connecting to nomad ...
21:59:04.062 main.go:122 ▶ INFO  Listening ...
21:59:04.068 nomad.go:168 ▶ ERRO  watch: unable to fetch allocations: Get http://10.230.45.40:4648/v1/allocations?index=1&wait=60000ms: EOF
21:59:04.068 nomad.go:189 ▶ ERRO  watch: unable to fetch evaluations: Get http://10.230.45.40:4648/v1/evaluations?index=1&wait=60000ms: EOF
21:59:04.070 nomad.go:210 ▶ ERRO  watch: unable to fetch jobs: Get http://10.230.45.40:4648/v1/jobs?index=1&wait=60000ms: EOF
21:59:04.070 nomad.go:231 ▶ ERRO  watch: unable to fetch nodes: Get http://10.230.45.40:4648/v1/nodes?index=1&wait=60000ms: EOF
21:59:04.071 nomad.go:251 ▶ ERRO  watch: unable to fetch members: Get http://10.230.45.40:4648/v1/agent/members?wait=60000ms: EOF

**Comment by obenziane2** [comment]
docker run -e NOMAD_ADDR=http://10.230.45.40:4646 -p 8000:3000 iverberk/nomad-ui:v0.3.1  worked thanks :)  good work!
