### ISSUE TITLE
Support Nomad 0.5

### ISSUE THREAD

**Issue by tmichaud314** [iverberk/nomad-ui#147]
Is Nomad 0.5 support planned?  Thanks!!

**Comment by jippi** [comment]
everything nomad 0.5 works except the `servers` left menu :)

**Comment by tmichaud314** [comment]
Hi @jippi,

After a small modification to backend/nomad.go due to a late change in the Nomad Client API (see below), I was able to compile everything and get it to work with the 0.5.0.  After clicking around, things generally seemed to work though I did notice the pie charts (on the landing page) did not display.  Were they removed?

THanks again!

```
diff --git a/backend/nomad.go b/backend/nomad.go
index 725b373..73ec799 100644
--- a/backend/nomad.go
+++ b/backend/nomad.go
@@ -114,8 +114,8 @@ func (n *Nomad) MembersWithID() ([]*AgentMemberWithID, error) {
                return nil, err
        }

-       ms := make([]*AgentMemberWithID, 0, len(members))
-       for _, m := range members {
+       ms := make([]*AgentMemberWithID, 0, len(members.Members))
+       for _, m := range members.Members {
                x, err := NewAgentMemberWithID(m)
                if err != nil {
                        return nil, errors.New(fmt.Sprintf("Failed to create AgentMemberWithID %s: %#v", err, m))
```

**Comment by jippi** [comment]
@tmichaud314 nice, can you submit a PR for it ? :)

and yes, the pie charts are gone :)

**Comment by tmichaud314** [comment]
@jippi Here is a PR for that small change: https://github.com/iverberk/nomad-ui/pull/148

**Comment by jippi** [comment]
Closing as PR is open
