### ISSUE TITLE
Mount nomad-ui on some possibly configurable prefix uri

### ISSUE THREAD

**Issue by bkmit** [iverberk/nomad-ui#15]
In case we want integrate nomad-ui with fabio https://github.com/eBay/fabio.git would be very useful to have ability to mount nomad-ui on some prefix like http://host.name.com/nomad-ui/...
It can be configurable by environment variable like NOMAD_PORT or hard coded.

**Comment by iverberk** [comment]
@bkmit that should be easy to do. I'll try to implement something this weekend.

**Comment by themalkolm** [comment]
@iverberk so is it serving part only or webapp also must be updated to respect prefix?

**Comment by iverberk** [comment]
@themalkolm yeah I think we need to take a look at the react router. I don't know if the current configuration is relative or not. Will take a look at it tonight.

**Comment by iverberk** [comment]
I looked into this a little more and I don't think we can create a dynamic subpath based on a parameter to serve the UI. The paths to the assets are determined at build time and although we can (and already did) modify the backend server to listen on a different subpath, the webapp will still try to load assets from /. My suggestion would be to use something like /ui (like Consul) or /nomad-ui  as a permanent subpath prefix. What do you guys think @bkmit @themalkolm ?

**Comment by themalkolm** [comment]
@iverberk are you really sure there is no way to fix it in react? On ws connect we can tell webapp where to look for assets, right?

**Comment by iverberk** [comment]
The problem is that the react app is never loaded (404). The index.html has references to a predefined path which we cannot set at runtime without some kind elaborate rewriting, which I don't think is worth the hassle.

**Comment by bkmit** [comment]
It is OK for me to have at least hard coded path. Better not so generic as consul's /ui.
nomad-ui - good.

**Comment by iverberk** [comment]
Ok, I'm going to use the 'nomad-ui' hardcoded path and put a redirect from / to /nomad-ui.

**Comment by iverberk** [comment]
This turning out harder than expected because of the way the backend and frontend are wired together (at build- and runtime). I'm also not really keen on hardcoding the nomad-ui path everywhere just for the sake of this. 

@bkmit is there really no other way to configure this in the loadbalancer? You can hardly expect every web application to provide a nice subpath for you? How do you deal with those cases? Normally I'd put something like nginx in front of my app to handle the redirect.

@themalkolm I've tried to make it work with relative paths but I really do not see a solution here. The index.html is generated at build time with links to the sources. If I make this relative it will just consider the root of the url, not any additional subpaths that might be there. 

I think we need to remove the configurable endpoint as well because it's not working atm. Do you have any suggestions?

**Comment by bkmit** [comment]
@iverberk: my main intent for this issue was to not introduce one more moving part (nginx) for integration. Unfortunately Go and JS is not my native tongues, and I can't make good quality PR beyond some 1-liners.
If it's not too hard to rewrite frontend and backend parts to not use absolute hrefs for assets and ws - this will fix a problem.

**Comment by far-blue** [comment]
I believe currently fabio cannot remap prefixes but it is something that's been requested and they are working on it. The current holdup is working out a format for the consul tag used as configuration. At the moment, foo.com/bar will get routed to the destination container at /bar but the plan is to allow foo.com/bar to route to / on a destination which would solve this problem.

I know people have differing opinions on where responsibility should lay for remapping a single url space into different microservices but I just take my lead from the Apache webserver which has been able to do it for decades through proxying and rewrite rules. If you look at the hundreds of thousands of php, ruby, python, perl, cgi and java apps out there - old-skool pre-microservice stuff, very few of them have support for a customisable prefix. If you want to mix services into a single url space - such as a website, a shopping cart, a blog and a ticketing system - you proxy via apache and rewrite rules.

I think it would be wrong to put effort into moving (statically or dynamically) the base url for nomad-ui. Instead, support should be given where possible to the developers of Fabio. If fabio isn't suitable then either mix-and-match with fabio and nginx etc. or simply switch from Fabio to nginx+consul-template and customise your rewrite rules as much as you need.

If I were planning on deploying all my live services as containers on a cluster fabric with consul I would certainly need (and want) to handle url mapping in stages - first routing by host, then by microservice / component. This would make handling ssl certs, logging and monitoring easier for me anyhow. Not that I have any plans to go that far at the moment :) It's also similar to how it currently works with load balancers and clusters of dedicated apache servers.

**Comment by bkmit** [comment]
@far-blue: I agree with your arguments about where is best place for url rewriting: it is proxy (nginx, apache, fabio).

**Comment by iverberk** [comment]
@bkmit would you be okay with me closing this issue? There are technical difficulties with a configurable prefix because of the way nomad-ui is architected. Forcing it would result in ugly hacks which I'm not quite prepared to do.

**Comment by bkmit** [comment]
It's OK.
