### ISSUE TITLE
missing parentheses

### ISSUE THREAD

**Issue by waterdudu** [iverberk/nomad-ui#154]
Frontend build error

Here is the error message:

```
ERROR in ./src/components/allocation/files.js

  239:11  error  Missing parentheses around multilines JSX                react/jsx-wrap-multilines
  239:11  error  Expected indentation of 8 space characters but found 10  react/jsx-indent
  256:11  error  Missing parentheses around multilines JSX                react/jsx-wrap-multilines
  256:11  error  Expected indentation of 8 space characters but found 10  react/jsx-indent
```

It seems parentheses are needed in `./src/components/allocation/files.js`

**Comment by jippi** [comment]
Hi @waterdudu 

As part of the rewrite in #153 this should be fixed :)

Are you working on a new feature, or just building it for local usage? :)

**Comment by waterdudu** [comment]
Thanks @jippi 

Just building it for local usage, it's quite a good tool to manage nomad jobs and allocations rather than using `nomad status`

**Comment by jippi** [comment]
@waterdudu okay, each release got binaries (go binary) which include everything :) 

https://github.com/iverberk/nomad-ui/releases

**Comment by waterdudu** [comment]
Great! @jippi
