### ISSUE TITLE
Assume that NOMAD_ADDR is localhost and NOMAD_PORT is 4646

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#18]
Won't it be great if `nomad-ui` followed logic from nomad itself and always assumed that you want to talk to the local service? So it works right away instead of throwing this:

```
2016/08/15 10:47:14 Please provide NOMAD_ADDR in the environment, which points to the Nomad server.
```

**Comment by iverberk** [comment]
Yeah, I suppose we could make it work this way, let me think about it for a bit. Might be confusing if people are running it in a Docker container because 127.0.0.1 would be local to the container. That's the original reasoning for always having to provide the Nomad location.

**Comment by themalkolm** [comment]
I would even prefer proper cli flags instead of environment variables. There should be a nice way to do both in golang I bet.

**Comment by themalkolm** [comment]
I think it is a good idea to ditch NOMAD_PORT completely as nomad did as well. NOMAD_ADDR has host:port so is enough. I think nomad-ui should mimic nomad configuration as much as possible.
