### ISSUE TITLE
Add servers tab to track online servers

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#19]
We run a small cluster of servers and it is very interesting to keep track how many of them alive as well, not nodes only.

**Comment by themalkolm** [comment]
Anyway, looks nice. Maybe I should start learning and hacking myself instead of writing issues for you :D

**Comment by iverberk** [comment]
@themalkolm PR's are always welcome! :-)

I've been testing with Nomad's 'dev' mode mostly, so I didn't exactly run into this. I'll setup a cluster where the servers are separated and see if can make a useful UI for them. Thanks for reporting!

**Comment by themalkolm** [comment]
@iverberk will add it then.
