### ISSUE TITLE
add default for NOMAD_PORT

### ISSUE THREAD

**Issue by ketzacoatl** [iverberk/nomad-ui#2]
While I remember a lot of things, it's usually details like this that elude me. I do remember there are three ports for nomad (4 something 46, 47, and 48), but I only vaguely remember that 6 is the something, and I forget which of 46, 47, 48 is _the_ "nomad server". Looking this up in nomad should be quick, but it took me a few pokes to remember that I should look at the agent section for configuration options.

Anyway.. that's a long way to say... defining a default that is correct / matches what the app expects from nomad would be great and save users one extra little detail to sort out when running nomad-ui for the first time.

I'd add this bit, but I'm not familiar enough with JS-tooling, and I see minimal bits in the production `settings.json` to work from.

Thanks for the great work!

**Comment by iverberk** [comment]
Ah ok, yeah good point actually. I wanted to make the port configurable in case anyone had a non-default setup but adding it as default definitely makes sense. I'll update the readme to use the default port, this should be probably be good enough for most people, agreed?

Thanks!

**Comment by ketzacoatl** [comment]
I usually opt for "set `$FOO` to override, but there's a default in place in case you don't set anything", but yea, a doc update works for those who read it :)

**Comment by iverberk** [comment]
Done!
