### ISSUE TITLE
websocket is always opened of plaintext

### ISSUE THREAD

**Issue by gnur** [iverberk/nomad-ui#20]
I've setup nomad-ui behind nginx for ssl termination and client verification but the websocket connection still seems to connect to ws:// instead of wss:// 

So I get these errors in the console (of chrome): 

`event.js:79Mixed Content: The page at 'https://nomadui.redacted/#/cluster?_k=j315or' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://nomadui.redacted/ws'. This request has been blocked; this endpoint must be available over WSS.`

**Comment by themalkolm** [comment]
I believe you want this commit https://github.com/iverberk/nomad-ui/commit/d14505e970fad2a885ce5680b5577799e45d21ca and it is not yet in any release.

**Comment by gnur** [comment]
Ah exactly, when can we expect this in a release? I was using the docker image for my convenience, might build it if a release isn't imminent.

**Comment by iverberk** [comment]
I will create a new release this afternoon. I'll also try to setup automated builds with Travis, time permitting.

**Comment by themalkolm** [comment]
@iverberk I added glide configuration and currently adding travis support to make it check that it still builds.

**Comment by iverberk** [comment]
@themalkolm Awesome, looking forward to it!

**Comment by themalkolm** [comment]
@iverberk I finished something that allows to automatically make releases. You can check it here https://github.com/themalkolm/nomad-ui in master branch. Tell me what you think.

**Comment by iverberk** [comment]
@themalkolm you've been busy!! :-D Looks really good. Is it possible for you to create (multiple) PR's (I think you made a number of adjustments/improvements)? That'll make it easier to assess the changes. Really excited to merge this.

**Comment by themalkolm** [comment]
@iverberk eh, depends if I have enough patience to make a pull request for every change

**Comment by iverberk** [comment]
@themalkolm you can batch up small ones of course, or make a big PR with all the changes. It's just easier to look at a diff than try to find what changed :-)

**Comment by iverberk** [comment]
This issue has been resolved and will be in the next release (working on that now).
