### ISSUE TITLE
Add nomad-0.4.1 support

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#44]
Lets add nomad-0.4.1 support and enable back code that was disabled in 2c2eb247e27a6339794fe5fbee28e475e46255bf.

Do we want to build different UI binaries for different nomad versions or we simply follow the edge?

**Comment by themalkolm** [comment]
Yeah, I know that everything is REST but still.

**Comment by iverberk** [comment]
yeah, good question. I think we should probably follow the edge but make sure that the latest released version of Nomad is fully supported. New features should probably have some kind of graceful degradation by not showing/using them if the Nomad server is not compatible. I'm going to think about this a little more.

**Comment by iverberk** [comment]
Let's follow the edge for now. I think 0.4.1 is released any day now. If people really need the file viewer they can use the previous version for a little while still.

**Comment by themalkolm** [comment]
It was released yesterday I believe.

**Comment by themalkolm** [comment]
I need a file viewer and streaming stdout/stderr so I will test this on 0.4.1 anyway 💃

**Comment by iverberk** [comment]
I've updated the dependency to 0.4.1 and re-enabled the log streaming.
