### ISSUE TITLE
Move webapp code to a separate folder

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#47]
This way we can have all part separated (something I really want):

* `/3rdparty`
* `/backend`
* `/webapp`
* Uber `Makefile` to build them all

What do you think?

**Comment by iverberk** [comment]
Yes, definitely makes sense with the current setup.

**Comment by themalkolm** [comment]
kk, will do it

**Comment by themalkolm** [comment]
Nah, won't do it.
