### ISSUE TITLE
Create a way to indicate in UI if backend is connected

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#48]
Currently UI doesn't show when it is unable to connect to backend. This way it is hard to get if backend is disconnected of there are simply no nodes/jobs/evaluations/etc.

**Comment by iverberk** [comment]
yeah, we should probably show some kind of modal dialog that show the disconnected status and disappears when the backend is connected.

**Comment by themalkolm** [comment]
I'm OK with a green/red dot somewhere instead. I don't like dialogs :D

**Comment by iverberk** [comment]
hmm, yeah it's really obtrusive but then again, if the backend is not connected the UI is basically useless. Maybe we could show a connection status in the sidebar.

**Comment by themalkolm** [comment]
Nomad itself can recover easily in cluster configuraiton. Death of a single server doesn't mean we are gone - it means this server is dead, it will simply reelect another leader. So we indicate that this *specified* server is OFF. If address provided was a DNS name, it is possible that after a while it will work again (some fail-over mechanism will update it to the working leader - we do this) and UI is usable again.

**Comment by themalkolm** [comment]
We can show pe-7s-attention next to NOMAD title or in status bar in this case with info in the tooltip why it is off.

**Comment by iverberk** [comment]
So maybe the nicer solution is to allow a list of servers to the backend configuration which we can round-robin in case of server failures. What do you think?

**Comment by iverberk** [comment]
oh wait, there are two issues at play here. Connecting to the backend websocket from the UI and the backend connecting to Nomad send, both might potentially fail.

**Comment by themalkolm** [comment]
Oh, yeah.

* Accept list of addresses in backend

* Indicate that backend is down
* Indicate that nomad is down

**Comment by themalkolm** [comment]
The easiest one is `backend being down` - we just need to track the timestamp of the last received message via websocket. Right? If it is too late - we are probably disconnected.

**Comment by iverberk** [comment]
For the ```backend being down``` case we can just monitor the websocket connection status. If it moves to a disconnected state we'll know that the backend has gone away or crashed. This can probably best be implemented with a background saga that checks the connection status regularly.

**Comment by iverberk** [comment]
On second thought, we could probably set an error handler on the websocket that dispatches an action on disconnect. I'll try to implement something for this.

**Comment by themalkolm** [comment]
Sounds fancy. I believe timestamp approach is much easier and more reliable. Yep, stupid but will work if you miss somehow errors or whatever.

**Comment by iverberk** [comment]
So what is ```too late``` in that case? The choice is pretty arbitrary and we would still need to have some kind of oversight process that actually checks this regularly.

It's not that fancy, the websocket object has native methods for handling disconnects which we can leverage. I'll create something for this.

**Comment by themalkolm** [comment]
kk

**Comment by themalkolm** [comment]
Maybe this issue must be split into multiple ones.

**Comment by iverberk** [comment]
yeah, the first one is a backend only issue and the third one is also mainly a backend issue. We could work on them separately.

**Comment by themalkolm** [comment]
Personally I fixed it for myself but merging upstream takes ages. I close all my tickets and move away from upstream.

**Comment by iverberk** [comment]
I'm sorry it took too long for you. I'm actually updating issues and merging PR's right now while on vacation. Unfortunately I can't respond to all issues and PR's on a daily basis. I'd like to thank you for your nice contributions and wish you the best.

**Comment by jippi** [comment]
@themalkolm @iverberk that was early in the project to fork? why not share commit-bit and put some trust in the combined result will in the end yield something better for everyone? maybe move it to a non-personal org as well to life it above just one person?

**Comment by jippi** [comment]
@themalkolm @iverberk did guys make up again or? 

@themalkolm where did you put your fork?

**Comment by themalkolm** [comment]
@jippi no, nothing happened. I moved to our corporate github repo so I can actually work on it during working hours as well.

**Comment by jippi** [comment]
@themalkolm is that public somewhere?

**Comment by themalkolm** [comment]
@jippi nope

**Comment by jippi** [comment]
@themalkolm do you plan to upstream any of it? :)

**Comment by themalkolm** [comment]
@jippi not now, sorry.
