### ISSUE TITLE
Why do we use /jobs prefix even for querying a single job?

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#49]
I just spent some quality time debugging piece of my code to realize that I was naturally using `/job/` prefix but we actually use `/jobs` everywhere!

```
<Route path="/jobs/:jobId/info" component={JobInfo} />
<Route path="/jobs/:jobId/allocations" component={JobAllocs} />
<Route path="/jobs/:jobId/evaluations" component={JobEvals} />
```

So what is the idea? Is it just a copy-paste legacy? Should we fix this?

**Comment by iverberk** [comment]
This is stuff for religious REST architecture debates (look up "rest plural" on google :-) but generally the reasoning is that we only have to worry about a single rest endpoint for the entire collection and that we can select a single element from the collection by specifying the id. I think this keeps things consistent and is quite nice as a design. Don't really want to change this.

**Comment by themalkolm** [comment]
Won't it make sense follow whatever decision is done in nomad itself? So less context switching and easier to guess what renders what.

**Comment by themalkolm** [comment]
So you just checked nomad and wanted to try it. You open v1/job/<some id> and see raw json output. Nice, now you want to see same data but in nomad ui. Where do you go? 

If we copy REST api at some extend - you just change hostname and it works - you get a nice web page.

If we change REST plurals (whatever) - you can't guess, you have to click, click, click to find it.

**Comment by themalkolm** [comment]
So we can add v1 prefix as well to copy it completely.

**Comment by iverberk** [comment]
The convention for plural form is also used by frameworks like Ruby on Rails, Django, Laravel, etc. So that's another source for choosing this convention.

**Comment by themalkolm** [comment]
No, the idea is to allow user to transfer his knowledge from nomads api to nomad-ui itself.

**Comment by iverberk** [comment]
ok, I can see the appeal, let me think about this. If we do this I want it to map 1:1 and not some kind of mixed bag.

**Comment by themalkolm** [comment]
Sorry if I'm pushy. I'm trying to hack something usable in couple of weeks and less context switches I have - less bugs I have. I just would like to keep `1:1` mapping with extensions on our side.

So, if you have v1/job/banana in nomad API, then you have v1/job/banana view as well. *But* we can always extend it i.e. add extra v1/job/banana/taskGroups that is not present in nomad itself.

I understand that you don't want to be dependent on them but I simply would go for copying while this project is so small and can't really afford to have it's own abstractions and tricky moments.

My use case is to use UI to get info easily and allow users to inspect how things are going. Mirroring api will make it faster for me to debug UI as well (I can always curl and compare what I should have received actually).

Copying names from nomad cli is also good idea to have less mental remapping. I just love how simple this UI is now and would like to keep it as close as possible to nomad's way of working with nomad i.e. API, nomad cli. We will always lag behind cli so its nice to be able effortlessly switch to API/cli whenever UI fails to provide.
