### ISSUE TITLE
Shouldn't headers be visible even if there are now rows?

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#55]
Currently we show nothing if there are now rows e.g. no allocations.

![image](https://cloud.githubusercontent.com/assets/864186/17812606/145353ba-6628-11e6-8ce3-37d0a8fbeae0.png)

Won't it make more sense to show empty table instead?

![image](https://cloud.githubusercontent.com/assets/864186/17812598/0690c58c-6628-11e6-8a54-0f0484b99314.png)

What do you think?

**Comment by iverberk** [comment]
Yeah, it's probably more indicative that there really are no allocations and not some random error happening.

**Comment by themalkolm** [comment]
OK
