### ISSUE TITLE
Proxy all requests to the nomad cluster?

### ISSUE THREAD

**Issue by gnur** [iverberk/nomad-ui#67]
I am running a nomad cluster and all communication for nomad is happening on the internal network and is not reachable on the outside.

I would like to use the nomad UI to easily see the state of the nomad cluster and the jobs in it. I use consul for service discovery and use nomad itself to run the nomad-ui docker container, but if I pass the "NOMAD_ADDR=nomad.service.consul" environment variable it will try to make calls from the browser (client) to "http://nomad.service.consul:4646" which obviously won't work.  Would it be possible to proxy all calls to nomad so nomad itself won't have to be exposed?

If not, to make the UI work it would be preferable to create an "internal" nomad address and a "public" nomad address, that way I could use nginx to proxy the calls to nomad with tls on a regular port (443).

**Comment by gnur** [comment]
I tried to proxy the requests, but somewhere it is hardcoded to make the requests to consul on http://, so the debugger ends up spewing messages like:

`client.js:839Mixed Content: The page at 'https://nomad.redacted.tld/#/cluster?_k=ts4h4c' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://https//nomad.redacted.tld:443/v1/evaluations?index=1'. This request has been blocked; the content must be served over HTTPS.`

**Comment by themalkolm** [comment]
Random thought. You can run nomad-ui on every node where server is running. This way you can discover the state of the world as it is on every cluster member. :D

**Comment by iverberk** [comment]
@gnur which version of nomad-ui are you using? Can you try v0.1.1 ? It seems you are using a version where the browser will directly connect to the Nomad server. I've since replaced this with a dedicated Go backend that connects to the server and that you can run inside the network. It will serve up the webapp if you hit it and make a websocket connection to receive updates.

**Comment by gnur** [comment]
Latest docker image seems to be working, perhaps the releases in github should be tagged with minimal versions as well, 0.1.0 has been the current release for a while now..

**Comment by iverberk** [comment]
@gnur that's good to hear. I'll take another look at the github releases, currently it's not working as expected, thanks for the pointer.
