### ISSUE TITLE
Expose port 3000 in the Dockerfile

### ISSUE THREAD

**Issue by far-blue** [iverberk/nomad-ui#72]
Hi :)

Rather than port mapping nomad-ui to a port on the host I make use of Fabio to proxy http requests through to containers. However, even when not port-mapped, a container must still expose a port for it to be available to talk to from other containers.

As such, currently (because Nomad can't handle exposed ports) I'm having to create a child image of Nomad-UI just so I can add an 'EXPOSE 3000' command in the Dockerfile.

Would it be possible for you to just add that line to your Dockerfile?

**Comment by iverberk** [comment]
Fixed in 81b500e04a70368d077a49c12357bd972fa1017c

@bkmit: @far-blue is using Fabio as well. Do you think his method will work for you as well, without the configurable prefix?

**Comment by iverberk** [comment]
Going to close as the original request is fixed, but please continue the discussion on Fabio because the configurable prefix option is troublesome.
