### ISSUE TITLE
'latest' docker image doesn't show any data

### ISSUE THREAD

**Issue by far-blue** [iverberk/nomad-ui#76]
Maybe this is something you are already aware of - the ws connection works fine but the data coming back has no data. The structures are being returned but the data arrays are empty '[]'.

I assume 'latest' is a 'work in progress'

**Comment by themalkolm** [comment]
No, they should have data :)

**Comment by iverberk** [comment]
I just tested the container and it seems to be producing data for me. I ran: docker run --rm -p 3000:3000 iverberk/nomad-ui:latest ./nomad-ui -address=http://x.x.x.x:4646

I will update the Dockerfile to create an entrypoint instead of command. Could there be some kind of communication problem @far-blue ?

**Comment by far-blue** [comment]
Maybe it's an issue with the NOMAD_ADDR env var value. I guess if all coms is now via websockets then that var should be set to the internal address for nomad rather than the one used by the browser externally.

**Comment by iverberk** [comment]
yes, the NOMAD_ADDR is only used by the backend component. Wherever you fire up the container, from there you should be able to connect to a nomad server specified with NOMAD_ADDR. The browser connection is only a websocket connection back to the backend component.

**Comment by far-blue** [comment]
Ah, right, yes. Previously my NOMAD_ADDR value was set to `nomad.server` - the external address. Now it needs to be `http://nomad.service.consul:4646`

**Comment by iverberk** [comment]
Can this be closed or do you have any further questions?

**Comment by far-blue** [comment]
happy to close it :)
