### ISSUE TITLE
'latest' - error with task groups tab for a job

### ISSUE THREAD

**Issue by far-blue** [iverberk/nomad-ui#77]
When I click on the task group tab for a job I get:

`main.ac0ba49ea4c8c4878963.js:11:26109 TypeError: (0,k["default"]) is not a function. (In '(0,k["default"])(n.ID)', '(0,k["default"])' is an instance of Object)`

After this, it looks like a second web socket is created and the two run in parallel and seem to cause some confusion until you reload the page.

**Comment by iverberk** [comment]
thanks for reporting this, I noticed it also. @themalkolm any idea what's happening? I can take a look later today.

**Comment by iverberk** [comment]
I just pushed a5d6335b98308635c267680e9a3b4f3f3a8f0a83, which should fix the error. It's now building so try it when a new image is pushed and let me know if it works.

**Comment by themalkolm** [comment]
Eh, js stuff. Fix if you know what and how :D

**Comment by themalkolm** [comment]
@iverberk Could you point me to some docs so I get what is the difference between them and what to use?

**Comment by far-blue** [comment]
I've tested and while the original error has gone away, when I click on a job I'm now getting the following every few seconds in the console and each error causes another websocket to be opened:

`Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BLTarget%2C%20RTarget%2C%20Operand%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
n — reactProdInvariant.js:32
a — traverseAllChildren.js:136:229
a — traverseAllChildren.js:85
o — traverseAllChildren.js:164
instantiateChildren — ReactChildReconciler.js:75
_reconcilerInstantiateChildren — ReactMultiChild.js:195
mountChildren — ReactMultiChild.js:228
_createInitialChildren — ReactDOMComponent.js:698
mountComponent — ReactDOMComponent.js:523
mountComponent — ReactReconciler.js:47
mountChildren — ReactMultiChild.js:240
_createInitialChildren — ReactDOMComponent.js:698
mountComponent — ReactDOMComponent.js:523
mountComponent — ReactReconciler.js:47
mountChildren — ReactMultiChild.js:240
_createInitialChildren — ReactDOMComponent.js:698
mountComponent — ReactDOMComponent.js:523
mountComponent — ReactReconciler.js:47
mountChildren — ReactMultiChild.js:240
_createInitialChildren — ReactDOMComponent.js:698
mountComponent — ReactDOMComponent.js:523
mountComponent — ReactReconciler.js:47
performInitialMount — ReactCompositeComponent.js:385
mountComponent — ReactCompositeComponent.js:260
mountComponent — ReactReconciler.js:47
updateChildren — ReactChildReconciler.js:122
_reconcilerUpdateChildren — ReactMultiChild.js:215
_updateChildren — ReactMultiChild.js:314
updateChildren — ReactMultiChild.js:301
_updateDOMChildren — ReactDOMComponent.js:941
updateComponent — ReactDOMComponent.js:759
receiveComponent — ReactDOMComponent.js:717
receiveComponent — ReactReconciler.js:126
updateChildren — ReactChildReconciler.js:110
_reconcilerUpdateChildren — ReactMultiChild.js:215
_updateChildren — ReactMultiChild.js:314
updateChildren — ReactMultiChild.js:301
_updateDOMChildren — ReactDOMComponent.js:941
updateComponent — ReactDOMComponent.js:759
receiveComponent — ReactDOMComponent.js:717
receiveComponent — ReactReconciler.js:126
_updateRenderedComponent — ReactCompositeComponent.js:761
_performComponentUpdate — ReactCompositeComponent.js:739
updateComponent — ReactCompositeComponent.js:658
receiveComponent — ReactCompositeComponent.js:552
receiveComponent — ReactReconciler.js:126
_updateRenderedComponent — ReactCompositeComponent.js:761
_performComponentUpdate — ReactCompositeComponent.js:739
updateComponent — ReactCompositeComponent.js:658
performUpdateIfNecessary — ReactCompositeComponent.js:566
performUpdateIfNecessary — ReactReconciler.js:158
s — ReactUpdates.js:151
perform — Transaction.js:138
perform — Transaction.js:138
perform — ReactUpdates.js:90
D — ReactUpdates.js:173
[native code]
closeAll — Transaction.js:204
perform — Transaction.js:151
batchedUpdates — ReactDefaultBatchingStrategy.js:63
u — ReactUpdates.js:201
r — ReactUpdateQueue.js:25
enqueueSetState — ReactUpdateQueue.js:210
setState — ReactComponent.js:64
handleChange — connect.js:301
[native code]
d — createStore.js:186
(anonymous function) — middleware.js:52
dispatch — applyMiddleware.js:45
(anonymous function) — proc.js:428
flush — asap.js:26
n — asap.js:14
D — proc.js:425
M — proc.js:379
r — proc.js:263
n — proc.js:333
o — proc.js:404
n — channel.js:79
(anonymous function) — channel.js:149
onmessage — event.js:42`

**Comment by far-blue** [comment]
Don't you just love React stack traces ;)

**Comment by iverberk** [comment]
hmm, I tried to reproduce this but couldn't. Any particular path you are following that triggers this behaviour?

**Comment by iverberk** [comment]
@far-blue do you have any more context or information on how to reproduce this? Can't seem to trigger it locally.

**Comment by far-blue** [comment]
I've just tried the latest 'latest' and the problem has gone away so I think it best to walk away and pretend nothing happened ;)

**Comment by iverberk** [comment]
Haha, ok, thanks for reporting back and if the issue returns be sure to let me know.
