### ISSUE TITLE
'latest' release name is confusing as it is not a release

### ISSUE THREAD

**Issue by themalkolm** [iverberk/nomad-ui#79]

**Comment by themalkolm** [comment]
Maybe SNAPSHOT will be a better name. Also it makes sense to mark it in github as pre-release to make sure people see it is not prod ready.

**Comment by iverberk** [comment]
good suggestions, I'll see if I can adjust the settings for travis.

**Comment by jippi** [comment]
isn't `latest` more or less `master` in git? and stable are tagged releases

**Comment by iverberk** [comment]
I think Github has some kind of predefined notion of latest because it's not working as I would expect. I would have hoped that the latest release would get overwritten with the latest commit to master, but it isn't.

**Comment by themalkolm** [comment]
@jippi latest was under 'release' tab so go wonder why it is not a release actually

**Comment by themalkolm** [comment]
Nah
