### ISSUE TITLE
Automatically release to DockerHub using automated build or Travic-CI

### ISSUE THREAD

**Issue by oryband** [iverberk/nomad-ui#84]
Hi!

Amazing project! Way to go and keep up the good work.

I've noticed v0.1.1 was released but the Docker image with this tag isn't yet available in DockerHub.
Can you please either set up an automated build on DockerHub or `docker build` and `docker push` in Travis?

Thanks.

**Comment by iverberk** [comment]
@oryband thanks for you kind words. I'll fix up the deployments.

**Comment by iverberk** [comment]
v0.1.2 was just released to github and Docker Hub.
