### ISSUE TITLE
UI fails on parsing TaskGroup "constraints" 

### ISSUE THREAD

**Issue by dropje86** [iverberk/nomad-ui#87]
When viewing a TaskGroup which has constraints configured the UI fails hard and doesn't recover until a hard reload.

Reproduce:
```hcl
job "nomad-ui" {
    region = "ams1"
    datacenters = ["ams1"]

    update {
        stagger = "5s"
        max_parallel = 1
    }

    group "frontend" {
        count = 2

        constraint {
            distinct_hosts = true
        }

        task "web" {
            driver = "docker"
            config {
                image = "iverberk/nomad-ui:v0.1.2"
                network_mode = "host"
            }

            env {
                NOMAD_ADDR = "http://nomad.service.consul:4646"
            }

            service {
                port = "http"

                tags = []

                check {
                    type = "http"
                    path = "/"
                    interval = "10s"
                    timeout = "2s"
                }
            }

            resources {
                cpu = 500
                memory = 128
                network {
                    mbits = 1
                    port "http" {}
                }
            }
        }
    }
}
```

Open up the UI and navigate to the nomad-ui job (which has a constraint configured)

**Comment by iverberk** [comment]
I could reproduce. Will try to fix asap. Thanks for giving a reproduction example.

**Comment by dropje86** [comment]
Thanks for your fast reply!

**Comment by iverberk** [comment]
This should be 'fixed' by 5531844735c8ae3db2a99f8cdd0e95d68e40ccc7. I've removed the display of constraints on the tables for the info and taskgroup tab of a job. There can be multiple constraints, each with a left target, operand and right target. This is not suitable for display in the table and should get a dedicated UI section if necessary. For now  the constraints can be viewed in the raw JSON. Can you confirm that this fixes the issue for you with the latest (Docker) build?

**Comment by dropje86** [comment]
It does! Thanks for the quick fix! Any chance you can actually tag this into a release?

**Comment by iverberk** [comment]
Since this addresses a severe bug I will tag a point release (v0.1.3).
