### ISSUE TITLE
[feature] tail functionality for logs

### ISSUE THREAD

**Issue by dropje86** [iverberk/nomad-ui#88]
### Feature request

When dealing with large amounts of log lines it becomes impossible to view them in the UI. It would be nice to be able to switch to a "tail" like view to not flood the browser with thousands of lines. This has been implemented in the [nomad cli](https://github.com/hashicorp/nomad/blob/32172ec06ac86cf5370fa9e59ab329bc72c088ba/command/fs.go#L250) but being able to do it from the browser would be even better.

**Comment by iverberk** [comment]
You're absolutely right. Any ideas on how many lines we should display? I'll probably implement this in the backend with the nomad cli options so that we never flood the browser with too many log lines. Maybe we could add an option to download the complete log if necessary?

**Comment by dropje86** [comment]
> Maybe we could add an option to download the complete log if necessary?
This sounds absolutely perfect..

I'm not sure on what would be a good default to display. Making it configurable might unnecessarily clutter the UI. You could say that a tail from the UI is equivalent to a `tail -n0 -f file.log` or just 15 lines or something. I assume that most clients should be able to have a resolution which supports that.

**Comment by iverberk** [comment]
Yeah, let's keep the number of lines to something sensible that will work on most resolutions. I'll try some settings. We should probably keep the height of the log display steady and allow scrolling through the logs that have been added during viewing of the tail. If you navigate away from the log view the whole thing gets reset. The download option should take care of wanting a complete output log.

**Comment by dropje86** [comment]
Sir, you are awesome.. And btw, this project really complements Nomad perfectly. Nicely done!

**Comment by iverberk** [comment]
Thanks for the kind words!

I have a lot of plans to extend the functionality to further complement Nomad, just need to find the time to implement it all :-)

**Comment by iverberk** [comment]
@dropje86 I'm working on this in #118, should be in somewhere this week.

**Comment by dropje86** [comment]
Thanks, I have been following 😄  👍
