### ISSUE TITLE
Create a backend component for polling and aggregation

### ISSUE THREAD

**Issue by iverberk** [iverberk/nomad-ui#9]
Reduce the burden of the client app by transferring the polling mechanisms to the backend. This would also eliminate the CORS restrictions. Maybe we can even do server side aggregation of information and potentially introduce security measures.

**Comment by iverberk** [comment]
Started working on this as it would significantly reduce complexity in the front-end app.

**Comment by ketzacoatl** [comment]
Would this result in being able to run the UI on a Nomad cluster, accessed over an SSH tunnel, and without the client being able to hit the nomad APIs directly?

**Comment by iverberk** [comment]
@ketzacoatl yes! I'm almost done with the backend implementation. You can run the backend anywhere you want, as long as it's able to reach your Nomad server. You can then hit it with the browser, directly or indirectly through an ssh tunnel, and it will serve up the client. The client makes a websocket connection back on the same host and port. All communication will happen through that single link. This gets rid of all the CORS stuff and the Nomad servers being hit directly by the webapp.

**Comment by ketzacoatl** [comment]
That is _really_ exciting! I'll keep an eye on this ticket and run tests when the updates are available. Thanks for all your work on this project, it's so great to see, and I hope it takes off with more contributors lending their time!

**Comment by adrianlop** [comment]
awesome work @iverberk

**Comment by iverberk** [comment]
I've completed the backend. Nomad-ui is now a single binary that serves both the backend and frontend. Please try it out and let me know if you find any bugs.

**Comment by ketzacoatl** [comment]
This works well in my testing (with the client connected over SSH tunnel). This is great!
