### ISSUE TITLE
"Unable to connect to the backend..." 

### ISSUE THREAD

**Issue by jippi** [iverberk/nomad-ui#99]
When trying to develop on the project locally, running `npm start` in `frontend/` and then accessing localhost:3333 I get `Unable to connect to the backend...` in the dev-console

I assume the go server would need to run, but `ws://localhost:3333/ws` is routed through webpack, and not into the go server (which is port 3000?)

**Comment by iverberk** [comment]
This currently requires a manual change in sagas/events.js. You need to set the url to the backend that you want to connect to.

For example:  const url = `${protocol}//127.0.0.1:3000/ws`;

**Comment by jippi** [comment]
Thanks
